name = "CryptoSim"
uuid = "d51330e2-fbdc-4705-9ef0-b6e3d6f06374"
version = "0.1.0"

[deps]
DoubleFloats = "497a8b3b-efae-58df-a0af-a86822472b78"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Mmap = "a63ad114-7e13-5084-954f-fe012c677804"
Parsers = "69de0a69-1ddd-5017-9359-2bf0b02dc9f0"
StructTypes = "856f2bd8-1eba-4b0a-8007-ebc267875bd4"
